#!/usr/bin/env ruby

#
# appstore_reviews
#
#  Fetch iTunes App Store reviews for each application, across all country stores
#   -- reads rating, author, subject and review body
#
# Notes
#  Derived from Erica Sadun's scraper: http://blogs.oreilly.com/iphone/2008/08/scraping-appstore-reviews.html
#  Apple's XML is purely layout-based, without much semantic relation to reviews, so the CSS paths below
#   are brittle.
#
# Jeremy Wohl
#   relevant post: http://igmus.org/2008/09/fetching-app-store-reviews
#
# TODO: spider additional review pages
#

require 'rubygems'
require 'hpricot'

# MODIFY THIS HASH WITH YOUR APP SET (grab the itunes store urls & pull the id params)
software = {
  # http://phobos.apple.com/WebObjects/MZStore.woa/wa/viewSoftware?id=289923007&mt=8
  'Domain Scout' => 289923007,
}

stores = {
  'United States' => 143441,
  'Argentina' => 143505,
  'Australia' => 143460,
  'Belgium' => 143446,
  'Brazil' => 143503,
  'Canada' => 143455,
  'Chile' => 143483,
  'China' => 143465,
  'Colombia' => 143501,
  'Costa Rica' => 143495,
  'Croatia' => 143494,
  'Czech Republic' => 143489,
  'Denmark' => 143458,
  'Deutschland' => 143443,
  'El Salvador' => 143506,
  'Espana' => 143454,
  'Finland' => 143447,
  'France' => 143442,
  'Greece' => 143448,
  'Guatemala' => 143504,
  'Hong Kong' => 143463,
  'Hungary' => 143482,
  'India' => 143467,
  'Indonesia' => 143476,
  'Ireland' => 143449,
  'Israel' => 143491,
  'Italia' => 143450,
  'Korea' => 143466,
  'Kuwait' => 143493,
  'Lebanon' => 143497,
  'Luxembourg' => 143451,
  'Malaysia' => 143473,
  'Mexico' => 143468,
  'Nederland' => 143452,
  'New Zealand' => 143461,
  'Norway' => 143457,
  'Osterreich' => 143445,
  'Pakistan' => 143477,
  'Panama' => 143485,
  'Peru' => 143507,
  'Phillipines' => 143474,
  'Poland' => 143478,
  'Portugal' => 143453,
  'Qatar' => 143498,
  'Romania' => 143487,
  'Russia' => 143469,
  'Saudi Arabia' => 143479,
  'Schweitz/Suisse' => 143459,
  'Singapore' => 143464,
  'Slovakia' => 143496,
  'Slovenia' => 143499,
  'South Africa' => 143472,
  'Sri Lanka' => 143486,
  'Sweden' => 143456,
  'Taiwan' => 143470,
  'Thailand' => 143475,
  'Turkey' => 143480,
  'United Arab Emirates' => 143481,
  'United Kingdom' => 143444,
  'Venezuela' => 143502,
  'Vietnam' => 143471,
  'Japan' => 143462,
}

# return a rating/subject/author/body hash
def fetch_reviews(software_id, store_id)
  reviews = []

  # TODO: parameterize type=Purple+Software
  cmd = sprintf(%{curl -s -A "iTunes/4.2 (Macintosh; U; PPC Mac OS X 10.2" -H "X-Apple-Store-Front: %s-1" } <<
                %{'http://ax.phobos.apple.com.edgesuite.net/WebObjects/MZStore.woa/wa/viewContentsUserReviews?id=%s&} <<
                %{pageNumber=0&sortOrdering=2&type=Purple+Software' | gunzip | xmllint --format -},
                store_id,
                software_id)

  doc = Hpricot.XML(`#{cmd}`)

  doc.search("Document > View > ScrollView > VBoxView > View > MatrixView > VBoxView:nth(0) > VBoxView > VBoxView").each do |e|
    review = {}
    
    strings = (e/:SetFontStyle)

    case strings.size
    when 8  # no "x customers found this review helpful" verbiage
      subset = strings[0..2]
    when 9  # yup
      subset = [ strings[0] ] + strings[2..3]
    else
      puts "warning: not sure about the structure here"
    end

    review[:rating] = e.inner_html.match(/alt="(\d+) star(s?)"/)[1].to_i
    review[:subject], review[:author], review[:body] = subset.map! { |x| x.inner_text.strip }
    review[:author] = review[:author][/by (.*)/, 1]
    
    reviews << review
  end

  reviews
end

# a simple command-line presentation
software.keys.sort.each do |software_key|
  puts "== App: #{software_key}"

  stores.keys.sort.each do |store_key|
    reviews = fetch_reviews(software[software_key], stores[store_key])

    if reviews.any?
      puts "=== Store: #{store_key}"
      
      reviews.each_with_index do |review, index|
        puts sprintf(%{%s %s, "%s", by %s}, review[:rating], review[:rating] > 1 ? "stars" : "star", review[:subject], review[:author])
        puts review[:body]
        puts "--\n" if index + 1 < reviews.size
      end
    end
  end
end
